/**
 * Derives the FIVE LETTERS word lists from SCOWL/ESDB and ENABLE. FIVE-LETTERS.md 12.
 *
 *   npx tsx tools/five-letters-words.ts --scowl <path to scowl-pre.txt> --enable <path to enable1.txt>
 *
 * Offline only: neither CI nor the browser fetches or runs this, because ESDB and
 * ENABLE are not committed (ESDB commit 1e5b7d3, ENABLE md5
 * 33f2b09e2d9dfb732fa16b5f05a5a8d1). The committed outputs rebuild byte for byte
 * from the same inputs.
 *
 * The rule, in the order applied:
 *   1. every lowercase a to z headword and inflection in scowl-pre.txt, at the
 *      smallest size level any of its lines gives it; separately, the smallest
 *      level at which it is a headword rather than only an inflection
 *   2. American only, entries tagged upper or abbr excluded, as PANGRAM
 *   3. in ENABLE
 *   4. exactly five letters
 *   5. minus data/word-lists/deny.txt
 * accepted.txt, the one list the browser validates against and every search
 * ranges over, is size 50 and below. answers.txt, the pool an answer may be drawn
 * from, is the accepted words that are a headword at size 35 or below, which
 * drops the plurals and past tenses the genre never uses as answers.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { argv, exit, stdout } from "node:process";

export const ACCEPTED_LEVEL = 50;
export const ANSWER_LEVEL = 35;
export const WORD_LENGTH = 5;
export const DENY_PATH = "data/word-lists/deny.txt";
export const ACCEPTED_PATH = "data/five-letters/accepted.txt";
export const ANSWERS_PATH = "data/five-letters/answers.txt";
export const WORDS_SOURCE_PATH = "src/games/five-letters/words.ts";

/** The runtime asset: the accepted list as one blob in a generated source file,
 *  so the page needs no fetch to validate a guess and plays offline. */
export function wordsSource(accepted: readonly string[]): string {
  return `/**
 * Layer 4. FIVE LETTERS accepted word list, the one runtime asset. FIVE-LETTERS.md 12.
 *
 * GENERATED by tools/five-letters-words.ts from data/five-letters/accepted.txt.
 * Do not edit by hand. Every guess is validated against it and every search
 * ranges over it. It is committed as source so the page needs no fetch and plays
 * offline from cache. It is not the answer pool: answers arrive, obfuscated, in
 * the day's manifest entry.
 *
 * SCOWL/ESDB notice: this list derives from SCOWL by Kevin Atkinson; the SCOWL
 * copyright and permission notice ships on the About page and in ASSETS.md.
 */

/* One space separated blob, split once at module load, so the source stays small
   and gzips as well as sorted text. */
const BLOB =
  "${accepted.join(" ")}";

export const ACCEPTED_WORDS: readonly string[] = BLOB.split(" ");
`;
}

const LINE = /^((?:\d+\s*(?:\[[^\]]*\]\s*)*)+):\s*(.*)$/;
const SIZE = /(?<![\w[])(\d+)(?=\s*(?:\[|$|\s))/g;
const WORD = /^[a-z]+$/;
const CODE = /^[A-Z][A-Za-z]*$/;

function clean(text: string): string {
  return text
    .replace(/<[^>]*>/g, "")
    .replace(/\{[^}]*\}/g, "")
    .replace(/#.*$/, "")
    .trim();
}

export interface Levels {
  /** Smallest level at which the word appears at all. */
  readonly any: Map<string, number>;
  /** Smallest level at which the word is a headword of its own line. */
  readonly head: Map<string, number>;
}

function lower(map: Map<string, number>, word: string, level: number): void {
  const known = map.get(word);
  if (known === undefined || level < known) map.set(word, level);
}

/** PANGRAM's parse, with headword status kept alongside. */
export function sizeLevels(scowl: string): Levels {
  const any = new Map<string, number>();
  const head = new Map<string, number>();
  let previous: string | null = null;
  for (const raw of scowl.split("\n")) {
    const line = LINE.exec(raw);
    if (line === null) continue;
    const levels = [...(line[1] as string).matchAll(SIZE)].map((match) => Number(match[1]));
    if (levels.length === 0) continue;
    const level = Math.min(...levels);
    const fields = (line[2] as string).split(":");
    const at = fields.findIndex((field) => field.includes("<"));
    if (at < 0) continue;
    const codes = fields
      .slice(0, at)
      .join(" ")
      .split(/\s+/)
      .filter((flag) => CODE.test(flag));
    if (codes.length > 0 && !codes.some((code) => code.startsWith("A"))) continue;
    const headField = fields[at] as string;
    const tags = /<([^>]*)>/.exec(headField)?.[1] ?? "";
    let word = clean(headField);
    const continuation = word === "-" || word === "";
    if (continuation) word = previous ?? "";
    else previous = word;
    /* After tracking the headword, so a continuation line after an upper or abbr
       entry still resolves to it, exactly as PANGRAM's parse does. */
    if (tags.includes("upper") || tags.includes("abbr")) continue;
    if (WORD.test(word)) {
      lower(any, word, level);
      if (!continuation) lower(head, word, level);
    }
    for (const field of fields.slice(at + 1)) {
      for (const piece of clean(field).split(",")) {
        const inflection = piece.trim();
        if (inflection !== "" && inflection !== "-" && WORD.test(inflection)) lower(any, inflection, level);
      }
    }
  }
  return { any, head };
}

export function deriveAccepted(levels: Levels, enable: ReadonlySet<string>, deny: ReadonlySet<string>): string[] {
  const out: string[] = [];
  for (const [word, level] of levels.any) {
    if (word.length !== WORD_LENGTH || level > ACCEPTED_LEVEL || !enable.has(word) || deny.has(word)) continue;
    out.push(word);
  }
  return out.sort();
}

export function deriveAnswers(levels: Levels, accepted: readonly string[]): string[] {
  return accepted.filter((word) => (levels.head.get(word) ?? Infinity) <= ANSWER_LEVEL);
}

export function lines(path: string): string[] {
  return readFileSync(path, "utf8")
    .split("\n")
    .map((word) => word.trim())
    .filter((word) => word.length > 0);
}

function flag(name: string): string | null {
  const at = argv.indexOf(`--${name}`);
  return at >= 0 && at + 1 < argv.length ? (argv[at + 1] as string) : null;
}

function main(): void {
  const scowlPath = flag("scowl");
  const enablePath = flag("enable");
  if (scowlPath === null || enablePath === null) {
    stdout.write("usage: five-letters-words --scowl <scowl-pre.txt> --enable <enable1.txt>\n");
    exit(1);
  }
  const levels = sizeLevels(readFileSync(scowlPath, "utf8"));
  const accepted = deriveAccepted(levels, new Set(lines(enablePath)), new Set(lines(DENY_PATH)));
  const answers = deriveAnswers(levels, accepted);
  writeFileSync(ACCEPTED_PATH, `${accepted.join("\n")}\n`);
  writeFileSync(ANSWERS_PATH, `${answers.join("\n")}\n`);
  writeFileSync(WORDS_SOURCE_PATH, wordsSource(accepted));
  stdout.write(`accepted ${String(accepted.length)} words, answers ${String(answers.length)} words\n`);
}

if (process.argv[1]?.replaceAll("\\", "/").endsWith("tools/five-letters-words.ts")) main();
