# -*- coding: utf-8 -*-
"""Build the downloadable versions of the DailyKit design system.

    python design-system/build-downloads.py

Reads this folder (tokens.json, components/, assets/) and writes design-system/downloads/:

    catalog.html                     one offline page: every component, live, in all four themes
    tokens.css, tokens.json          the tokens as CSS custom properties, and as data
    icons/ui/*.svg                   the eight UI icons (currentColor)
    icons/games/*.svg                each game's mark, light and dark accent
    logos/*.svg                      each game's badge and badge + wordmark lockup, light and dark
    dailykit-*.zip                   the same, packaged (fixed timestamps: a rebuild is byte-stable)

Standard library plus Node (only to read the icon and game tables out of components/bundle.js).
"""
import json, os, re, subprocess, sys, zipfile, html

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "downloads")
STAMP = (2026, 9, 21, 0, 0, 0)


def read(p):
    with open(os.path.join(HERE, p), encoding="utf8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def write(rel, text):
    p = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf8", newline="\n") as f:
        f.write(text)


# ---------------------------------------------------------------- tokens.css
def tokens_css(tok):
    themes = [t["id"] for t in tok["color"]["themes"]]
    first = themes[0]

    def val(t, th):
        v = t["value"]
        if isinstance(v, str):
            return v
        return v.get(th, v.get(first))

    def alias(v):
        m = re.fullmatch(r"\{(.+)\}", v)
        return f"var(--{m.group(1)})" if m else v

    out = ["/* DailyKit design tokens. Generated by build-downloads.py from tokens.json: do not edit. */"]
    for i, th in enumerate(themes):
        sel = f':root, [data-theme="{th}"]' if th == first else f'[data-theme="{th}"]'
        lines = [f"  --{t['name']}: {alias(val(t, th))};" for t in tok["color"]["tokens"]]
        for t in tok.get("shadow", {}).get("tokens", []):
            lines.append(f"  --{t['name']}: {val(t, th)};")
        out.append(sel + " {\n" + "\n".join(lines) + "\n}")
    root = []
    for fam in ("spacing", "radius"):
        for t in tok.get(fam, {}).get("tokens", []):
            root.append(f"  --{t['name']}: {t['value']};")
    for k, v in tok["type"]["families"].items():
        root.append(f"  --font-{k}: {v};")
    out.append(":root {\n" + "\n".join(root) + "\n}")
    for g in tok["type"]["groups"]:
        for s in g["styles"]:
            fam = s.get("family") or g["family"]
            decl = [f"font-family: var(--font-{fam})", f"font-size: {s['fontSize']}", f"line-height: {s['lineHeight']}",
                    f"font-weight: {s['fontWeight']}"]
            if s.get("letterSpacing") not in (None, "", "0"):
                decl.append(f"letter-spacing: {s['letterSpacing']}")
            out.append(f".{s['name']} {{ " + "; ".join(decl) + "; }")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- bundle tables via node
def bundle_tables():
    js = os.path.join(HERE, "components", "bundle.js").replace("\\", "/")
    code = ("global.window={};eval(require('fs').readFileSync(%s,'utf8'));"
            "const K=window.DailyKit;console.log(JSON.stringify({games:K.GAMES,icons:K.ICONS,labels:K.ICON_LABEL}))" % json.dumps(js))
    r = subprocess.run(["node", "-e", code], capture_output=True, text=True, encoding="utf8", check=True)
    return json.loads(r.stdout)


# ---------------------------------------------------------------- svg files
def hsl(h, s, l):
    return f"hsl({h} {s}% {l}%)"


def hue_of(game):
    return int(re.search(r"hsl\((\d+)", game["accent_light"]).group(1))


def svg_wrap(inner, size, color, extra=""):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="{size}" height="{size}" '
            f'color="{color}"{extra}>{inner}</svg>\n')


def build_svgs(tok, tables):
    tokens = {t["name"]: t for t in tok["color"]["tokens"]}
    files = []
    for name, inner in tables["icons"].items():
        rel = f"icons/ui/{name}.svg"
        write(rel, svg_wrap(inner, 24, "hsl(0 0% 12%)", f' role="img" aria-label="{html.escape(tables["labels"][name])}"'))
        files.append(rel)
    for g in tables["games"]:
        t = tokens["game-" + g["id"]]["value"]
        light, dark = t["light"], t["dark"]
        h = int(re.search(r"hsl\((\d+)", light).group(1))
        on_light = "hsl(0 0% 12%)" if g.get("on") == "dark" else "hsl(0 0% 100%)"
        on_dark = "hsl(220 12% 10%)"
        name = g["name"]
        for variant, accent, text, icon_on in (("light", light, "hsl(0 0% 12%)", on_light), ("dark", dark, "hsl(0 0% 94%)", on_dark)):
            # the mark alone, in the accent
            rel = f"icons/games/{g['id']}-{variant}.svg"
            write(rel, svg_wrap(g["icon"], 96, accent, f' role="img" aria-label="{html.escape(name)}"'))
            files.append(rel)
            # the badge: accent square holding the mark
            badge = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="256" height="256" role="img" aria-label="{html.escape(name)}">'
                     f'<rect width="64" height="64" rx="12" fill="{accent}"/>'
                     f'<g transform="translate(14 14) scale(1.5)" color="{icon_on}">{g["icon"]}</g></svg>\n')
            rel = f"logos/{g['id']}-badge-{variant}.svg"
            write(rel, badge)
            files.append(rel)
            # the lockup: badge + name, transparent background
            width = 80 + int(len(name) * 21) + 8
            lock = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 64" width="{width}" height="64" role="img" aria-label="{html.escape(name)}">'
                    f'<rect width="64" height="64" rx="12" fill="{accent}"/>'
                    f'<g transform="translate(14 14) scale(1.5)" color="{icon_on}">{g["icon"]}</g>'
                    f'<text x="80" y="43" font-family="system-ui, -apple-system, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif" '
                    f'font-size="28" font-weight="700" letter-spacing="1.1" fill="{text}">{html.escape(name)}</text></svg>\n')
            rel = f"logos/{g['id']}-lockup-{variant}.svg"
            write(rel, lock)
            files.append(rel)
    return files


# ---------------------------------------------------------------- catalog.html
def components():
    out = []
    root = os.path.join(HERE, "components")
    for name in sorted(os.listdir(root)):
        d = os.path.join(root, name)
        pv = os.path.join(d, "preview.html")
        if not os.path.isfile(pv):
            continue
        prev = read(f"components/{name}/preview.html")
        m = re.match(r"<!--\s*@dsCard\s+([^>]*?)-->", prev)
        attrs = dict(re.findall(r'(\w+)=("[^"]*"|\d+)', m.group(1))) if m else {}
        group = attrs.get("group", "").strip('"') or "Other"
        height = int(attrs.get("height", "160").strip('"'))
        rd = f"components/{name}/README.md"
        out.append({"name": name, "group": group, "height": height, "preview": prev,
                    "readme": read(rd) if os.path.isfile(os.path.join(HERE, rd)) else ""})
    return out


CATALOG = r"""<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DailyKit design system catalog</title>
<style>
__TOKENS__
__BUNDLECSS__
</style>
<style>
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:var(--font-sans);line-height:1.5}
header.top{position:sticky;top:0;z-index:5;display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center;padding:10px 16px;background:var(--surface);border-bottom:1px solid var(--line)}
header.top h1{margin:0;font-size:1rem;letter-spacing:.04em;flex:1 1 auto}
.themes{display:flex;gap:6px;flex-wrap:wrap}
.themes button{min-height:36px;padding:0 12px;border:1px solid var(--text-dim);border-radius:var(--radius);background:var(--surface-raised);color:var(--text);font:inherit;font-size:.85rem;cursor:pointer}
.themes button[aria-pressed="true"]{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}
main{max-width:1000px;margin:0 auto;padding:16px}
nav.toc{display:flex;flex-wrap:wrap;gap:6px 12px;margin:0 0 16px;font-size:.85rem}
nav.toc a{color:var(--accent)}
h2.group{margin:32px 0 8px;font-size:.8rem;letter-spacing:.08em;text-transform:uppercase;color:var(--text-dim)}
.card{margin:0 0 20px;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface-raised);overflow:hidden}
.card h3{margin:0;padding:8px 12px;font-size:.95rem;border-bottom:1px solid var(--line);background:var(--surface)}
.card iframe{display:block;width:100%;border:0;background:var(--bg)}
.card details{border-top:1px solid var(--line);padding:8px 12px;font-size:.9rem}
.card summary{cursor:pointer;color:var(--text-dim)}
.md p{margin:.5em 0}.md code{font-family:var(--font-mono);font-size:.9em;background:var(--surface);padding:0 3px;border-radius:3px}
.md table{border-collapse:collapse;width:100%;font-size:.85rem;margin:.5em 0}.md th,.md td{border:1px solid var(--line);padding:4px 8px;text-align:left;vertical-align:top}
.md ul{padding-left:1.2em}.md h1,.md h2,.md h3{margin:1em 0 .3em}.md h1{font-size:1.3rem}.md h2{font-size:1.1rem}.md h3{font-size:1rem}
.md blockquote{margin:.5em 0;padding:0 12px;border-left:3px solid var(--line);color:var(--text-dim)}
.sw{display:grid;grid-template-columns:200px repeat(4,1fr);gap:0;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden;font-size:.8rem}
.sw div{padding:6px 8px;border-bottom:1px solid var(--line);min-width:0;overflow-wrap:anywhere}
.sw .h{background:var(--surface);font-weight:700}
.sw .chip{display:inline-block;width:14px;height:14px;border-radius:3px;border:1px solid var(--text-dim);vertical-align:-2px;margin-right:6px}
@media (max-width:640px){.sw{grid-template-columns:120px repeat(4,1fr)}}
</style>
</head>
<body>
<header class="top"><h1>DAILYKIT DESIGN SYSTEM</h1><div class="themes" role="group" aria-label="Theme"></div></header>
<main>
<nav class="toc" id="toc"></nav>
<section id="readme" class="md"></section>
<h2 class="group">Colour tokens</h2><div id="tokens"></div>
<div id="cards"></div>
<p class="md" style="color:var(--text-dim);margin-top:40px">Generated by design-system/build-downloads.py. Every preview above is the live component, rendered by components/bundle.js, in the theme you pick.</p>
</main>
<script>
var DATA = __DATA__;
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function inline(s){return esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>')}
function md(src){
  var lines=src.split('\n'),out=[],i=0;
  while(i<lines.length){
    var l=lines[i];
    if(/^\s*$/.test(l)){i++;continue}
    var h=/^(#{1,3}) (.*)/.exec(l); if(h){out.push('<h'+h[1].length+'>'+inline(h[2])+'</h'+h[1].length+'>');i++;continue}
    if(/^>/.test(l)){var q=[];while(i<lines.length&&/^>/.test(lines[i])){q.push(lines[i].replace(/^>\s?/,''));i++}out.push('<blockquote>'+inline(q.join(' '))+'</blockquote>');continue}
    if(/^\|/.test(l)&&/^\|[\s\-:|]+\|$/.test(lines[i+1]||'')){var rows=[];while(i<lines.length&&/^\|/.test(lines[i])){rows.push(lines[i]);i++}
      var cells=function(r){return r.replace(/^\||\|$/g,'').split('|').map(function(c){return c.trim()})};
      var t='<table><thead><tr>'+cells(rows[0]).map(function(c){return '<th>'+inline(c)+'</th>'}).join('')+'</tr></thead><tbody>';
      rows.slice(2).forEach(function(r){t+='<tr>'+cells(r).map(function(c){return '<td>'+inline(c)+'</td>'}).join('')+'</tr>'});out.push(t+'</tbody></table>');continue}
    if(/^\s*[-*] /.test(l)){var li=[];while(i<lines.length&&/^\s*[-*] /.test(lines[i])){li.push('<li>'+inline(lines[i].replace(/^\s*[-*] /,''))+'</li>');i++}out.push('<ul>'+li.join('')+'</ul>');continue}
    var p=[];while(i<lines.length&&!/^\s*$/.test(lines[i])&&!/^(#{1,3} |>|\|)/.test(lines[i])&&!/^\s*[-*] /.test(lines[i])){p.push(lines[i]);i++}
    out.push('<p>'+inline(p.join(' '))+'</p>');
  }
  return out.join('\n');
}
var THEMES=[['light','Light'],['dark','Dark'],['light-contrast','Light, high contrast'],['dark-contrast','Dark, high contrast']];
var current='light';
function frameDoc(c,theme){
  return '<!doctype html><html data-theme="'+theme+'"><head><meta charset="utf-8"><style>'+DATA.tokens+'\n'+DATA.bundleCss+'</style><script>'+DATA.bundleJs.replace(/<\//g,'<\\/')+'<\/script></head>'+c.preview+'</html>';
}
function setTheme(t){
  current=t;document.documentElement.dataset.theme=t;
  Array.prototype.forEach.call(document.querySelectorAll('.themes button'),function(b){b.setAttribute('aria-pressed',String(b.dataset.t===t))});
  Array.prototype.forEach.call(document.querySelectorAll('iframe'),function(f){try{f.contentDocument.documentElement.dataset.theme=t}catch(e){}});
}
var tb=document.querySelector('.themes');
THEMES.forEach(function(t){var b=document.createElement('button');b.type='button';b.textContent=t[1];b.dataset.t=t[0];b.onclick=function(){setTheme(t[0])};tb.appendChild(b)});
document.getElementById('readme').className='md';document.getElementById('readme').innerHTML=md(DATA.readme);
// colour tokens
var tk=document.getElementById('tokens'),g='<div class="sw"><div class="h">token</div>'+THEMES.map(function(t){return '<div class="h">'+t[1]+'</div>'}).join('');
DATA.colors.forEach(function(c){g+='<div><code>'+esc(c.name)+'</code></div>'+THEMES.map(function(t){var v=c.value[t[0]]||c.value.light;return '<div><span class="chip" style="background:'+esc(v)+'"></span>'+esc(v)+'</div>'}).join('')});
tk.innerHTML=g+'</div>';
// component cards, grouped
var groups={},order=[];DATA.components.forEach(function(c){if(!groups[c.group]){groups[c.group]=[];order.push(c.group)}groups[c.group].push(c)});
var cards=document.getElementById('cards'),toc=document.getElementById('toc');
order.forEach(function(gn){
  var h=document.createElement('h2');h.className='group';h.textContent=gn;h.id='g-'+gn.replace(/\W+/g,'-');cards.appendChild(h);
  var a=document.createElement('a');a.href='#'+h.id;a.textContent=gn;toc.appendChild(a);
  groups[gn].forEach(function(c){
    var d=document.createElement('section');d.className='card';d.id='c-'+c.name;
    d.innerHTML='<h3>'+esc(c.name)+'</h3>';
    var f=document.createElement('iframe');f.title=c.name+' preview';f.style.height=c.height+'px';f.setAttribute('loading','lazy');
    f.srcdoc=frameDoc(c,current);d.appendChild(f);
    if(c.readme){var de=document.createElement('details');de.innerHTML='<summary>Guidelines</summary><div class="md">'+md(c.readme)+'</div>';d.appendChild(de)}
    cards.appendChild(d);
  });
});
setTheme('light');
</script>
</body>
</html>
"""


def build_catalog(tok, css, comps):
    data = {
        "tokens": css,
        "bundleCss": read("components/bundle.css"),
        "bundleJs": read("components/bundle.js"),
        "readme": re.sub(r"^# DailyKit design system\n\n(>.*\n)+\n", "# DailyKit design system\n\n", read("README.md")),
        "colors": tok["color"]["tokens"],
        "components": comps,
    }
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    page = (CATALOG.replace("__TOKENS__", css).replace("__BUNDLECSS__", data["bundleCss"]).replace("__DATA__", payload))
    write("catalog.html", page)


# ---------------------------------------------------------------- zips
def add(z, arcname, path=None, text=None):
    zi = zipfile.ZipInfo(arcname, STAMP)
    zi.compress_type = zipfile.ZIP_DEFLATED
    zi.external_attr = 0o644 << 16
    if text is None:
        with open(path, "rb") as f:
            z.writestr(zi, f.read())
    else:
        z.writestr(zi, text.encode("utf8"))


def walk(rel_dir, skip=()):
    base = os.path.join(HERE, rel_dir)
    for dp, dn, fn in os.walk(base):
        dn.sort()
        for f in sorted(fn):
            p = os.path.join(dp, f)
            rel = os.path.relpath(p, HERE).replace("\\", "/")
            if any(rel == s or rel.startswith(s.rstrip("/") + "/") for s in skip):
                continue
            yield rel, p


def make_zip(name, entries, prefix):
    p = os.path.join(OUT, name)
    with zipfile.ZipFile(p, "w") as z:
        for arc, path in entries:
            add(z, f"{prefix}/{arc}", path=path)
    return p


def build_zips(files_written):
    o = lambda rel: os.path.join(OUT, rel)
    h = lambda rel: os.path.join(HERE, rel)
    # 1 source: the design system as authored
    src = [(rel, p) for rel, p in walk(".", skip=("downloads",))]
    make_zip("dailykit-design-system-source.zip", src, "dailykit-design-system")
    # 2 tokens
    make_zip("dailykit-tokens.zip", [("tokens.json", h("tokens.json")), ("tokens.css", o("tokens.css"))], "dailykit-tokens")
    # 3 components: the runnable library and its types
    comp = [("bundle.js", h("components/bundle.js")), ("bundle.css", h("components/bundle.css")), ("index.d.ts", h("components/index.d.ts")),
            ("tokens.css", o("tokens.css")), ("catalog.html", o("catalog.html"))]
    p = os.path.join(OUT, "dailykit-components.zip")
    with zipfile.ZipFile(p, "w") as z:
        for arc, path in comp:
            add(z, "dailykit-components/" + arc, path=path)
        add(z, "dailykit-components/example.html", text=EXAMPLE)
    # 4 icons and logos as SVG
    ic = [(rel, o(rel)) for rel in files_written] + [(rel, p) for rel, p in walk("assets/Logos")]
    make_zip("dailykit-icons-and-logos-svg.zip", ic, "dailykit-icons-and-logos")
    # 4b the same logos as PNG, if they have been rendered (see README: a browser renders them from the SVGs)
    pngs = []
    pd = o("logos/png")
    if os.path.isdir(pd):
        pngs = [f"logos/png/{f}" for f in sorted(os.listdir(pd)) if f.endswith(".png")]
        make_zip("dailykit-logos-png.zip", [(rel, o(rel)) for rel in pngs], "dailykit-logos-png")
    # 5 everything
    allf = [(rel, p) for rel, p in walk(".", skip=("downloads",))]
    allf += [(f"downloads/{rel}", o(rel)) for rel in sorted(os.listdir(OUT)) if os.path.isfile(o(rel)) and not rel.endswith(".zip")]
    allf += [(f"downloads/{rel}", o(rel)) for rel in files_written + pngs]
    seen, uniq = set(), []
    for a, pth in allf:
        if a not in seen:
            seen.add(a); uniq.append((a, pth))
    make_zip("dailykit-design-system-complete.zip", uniq, "dailykit-design-system")


EXAMPLE = """<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DailyKit components: minimal example</title>
<link rel="stylesheet" href="tokens.css">
<link rel="stylesheet" href="bundle.css">
<script src="bundle.js"></script>
</head>
<body>
<div id="app" style="max-width:420px;margin:0 auto"></div>
<script>
  var K = window.DailyKit, app = document.getElementById('app');
  app.appendChild(K.Header({ title: 'WORD LADDER', fit: 'tight', left: [{ icon: 'home', label: 'All games' }], right: [{ icon: 'help', label: 'How to play' }] }));
  var g = document.createElement('div'); g.style.setProperty('--accent', 'var(--game-word-ladder)'); g.style.padding = '16px';
  g.appendChild(K.WordLadderBoard({ status: 'On CORD, climbing to WARM.', goal: 'Goal: WARM - par 4', word: 'cord', armed: 0, start: 'cold', rungs: [{ word: 'cord', progress: 1 }] }));
  app.appendChild(g);
  // themes: light, dark, light-contrast, dark-contrast
  // document.documentElement.dataset.theme = 'dark';
</script>
</body>
</html>
"""

README = """# Downloads

Everything in the design system, in the shape you would want to take away. Rebuild any time with `python design-system/build-downloads.py` (Python 3 and Node; nothing to install). The zips use fixed timestamps, so a rebuild with no changes produces the same bytes; for that reason **none of this folder is committed** (`.gitignore` excludes `design-system/downloads/` entirely) — only `build-downloads.py` and the source it reads are. Run the script to get them.

| file | what it is |
| --- | --- |
| `dailykit-design-system-complete.zip` | everything below plus the authored source: the one file to keep |
| `dailykit-design-system-source.zip` | the design system as authored: `tokens.json`, `components/`, `assets/`, the README brand book |
| `dailykit-components.zip` | the runnable library: `bundle.js`, `bundle.css`, `index.d.ts`, `tokens.css`, `catalog.html` and an `example.html` that renders a game board |
| `dailykit-tokens.zip` | `tokens.json` (data) and `tokens.css` (custom properties for all four themes) |
| `dailykit-icons-and-logos-svg.zip` | every icon and logo as an SVG file, plus the suite icon in SVG and PNG |
| `dailykit-logos-png.zip` | every badge and lockup as PNG at 2x (badge 512 by 512, lockups 128 high), transparent background |
| `catalog.html` | one offline page: every component live, the guidelines under each, and a switch for the four themes. Open it in a browser |
| `tokens.css`, `tokens.json` | the tokens, unzipped |
| `icons/ui/*.svg` | the eight UI icons, 24 by 24, `currentColor` (set `color` on the element, or the file's own `color` attribute) |
| `icons/games/<game>-light.svg`, `-dark.svg` | each of the eleven games' mark in that game's accent for a light or a dark page |
| `logos/<game>-badge-light.svg`, `-dark.svg` | the square badge: the accent with the mark cut in |
| `logos/<game>-lockup-light.svg`, `-dark.svg` | badge plus the game's name, on a transparent ground |
| `logos/png/*.png` | the same badges and lockups rendered to PNG. Not produced by this script: a browser rasterised each SVG at 2x. The `-dark` lockups have light text for a dark page, so they look empty on white |

## Notes

- The icon set and the per-game marks are **proposals**: the shipped code has no icon set by decision (`ASSETS.md`). They are drop-in for when that changes.
- The lockup text is live SVG text in the suite's system-font stack, so it renders in whatever system font the viewer has; convert it to outlines in a vector editor before using it where the font matters.
- Games not yet offered as playable (`status: "planned"` in `src/shell/registry.ts`) have marks here too; show them dimmed, as the hub does.
- Colour values are the tokens': `hsl()` accents, light `62% / 40%`, dark `62% / 62%`. Five hues have white text under 4.5:1 in the light theme, so their badges use dark marks (see the README's accent audit).
"""


def main():
    os.makedirs(OUT, exist_ok=True)
    tok = json.loads(read("tokens.json"))
    css = tokens_css(tok)
    write("tokens.css", css)
    write("tokens.json", read("tokens.json"))
    tables = bundle_tables()
    files = build_svgs(tok, tables)
    build_catalog(tok, css, components())
    write("README.md", README)
    build_zips(files)
    n = sum(len(f) for _, _, f in os.walk(OUT))
    print(f"downloads: {n} files in {OUT}")


if __name__ == "__main__":
    main()
